---
- name: ensure gpg available
  apt:
    name: gnupg
    state: present
    update_cache: true

- name: add Mongodb source key
  apt_key:
    url: "{{ mongodb_source_key }}"
    state: present

- name: add Mongodb source
  apt_repository:
    repo: "{{ mongodb_source_url }}"
    filename: "mongodb-org-{{ mongodb_version }}"
    state: present

- name: install mongodb
  apt:
    name: mongodb-org
    state: present

- name: enable mongodb services
  systemd:
    name: mongod
    state: started
    enabled: true
  become: true
